# Generated by Django 5.0.7 on 2024-08-01 20:56

import Books.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='book title')),
                ('book_type', models.CharField(choices=[('EB', 'E-book'), ('AU', 'Audio-book')], max_length=2)),
                ('cover_img', models.ImageField(upload_to=Books.models.book_dir)),
                ('publication_date', models.DateField()),
                ('no_pages', models.IntegerField(blank=True, null=True)),
                ('LibraryId', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name="Let's learn ID")),
                ('isbn10', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='ISBN-10')),
                ('isbn13', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN-13')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='Books.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_reader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Books.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.reader')),
            ],
        ),
        migrations.CreateModel(
            name='BookActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('download', 'Download'), ('share', 'Share')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.reader')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader_book', to='Books.reader'),
        ),
        migrations.CreateModel(
            name='ReadingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reading', 'Reading'), ('finished', 'Finished')], max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.reader')),
            ],
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'publisher'), name='unique_title_publisher'),
        ),
    ]
