# Generated by Django 5.0.7 on 2024-08-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_reader_city_reader_date_of_birth_reader_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingstatus',
            name='status',
            field=models.CharField(choices=[('reading', 'Reading'), ('finished', 'Finished'), ('want to', 'Want to Read')], max_length=20),
        ),
    ]
