# Generated by Django 5.0.7 on 2024-08-18 21:04

import Books.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_book_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_name', models.CharField(max_length=100, verbose_name='heading')),
                ('heading_image', models.ImageField(blank=True, null=True, upload_to=Books.models.book_dir)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
        ),
        migrations.CreateModel(
            name='SubHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_name', models.CharField(max_length=100, verbose_name='subheading')),
                ('heading_image', models.ImageField(blank=True, null=True, upload_to=Books.models.book_dir)),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.heading')),
            ],
        ),
    ]
