# Generated by Django 5.0.7 on 2024-08-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_heading_heading_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heading',
            old_name='heading_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subheading',
            old_name='heading_name',
            new_name='title',
        ),
    ]
